Repository vaadin/flow-and-components-documentation, pull requests merged in 2019-04, with the labels that each got.

#559 correct reference syntax
  documentation/advanced/tutorial-bootstrap.asciidoc
Labels: to be cherry picked

#557 Correct doc layout format
  documentation/routing/tutorial-routing-exception-handling.asciidoc
Labels: to be cherry picked

#569 Fix ParentPrefix -> RoutePrefix
  documentation/routing/tutorial-router-layout.asciidoc
Labels: to be cherry picked to V13

#544 Remove the bower and webjar references from the documentation
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/IconButton.java
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/InProject.java
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/b/PaperSlider.java
  documentation/web-components/creating-an-in-project-web-component.asciidoc
  documentation/web-components/creating-another-type-of-addon.asciidoc
  documentation/web-components/creating-java-api-for-a-web-component.asciidoc
  documentation/web-components/debugging-a-web-component-integration.asciidoc
  documentation/web-components/introduction-to-webcomponents.asciidoc
Labels: npm

#576 Remove bower goals.
  documentation/production/tutorial-production-mode-basic.asciidoc
Labels: npm

#591 2.0 merge master
  documentation/Overview.asciidoc
  documentation/advanced/tutorial-bootstrap.asciidoc
  documentation/advanced/tutorial-service-init-listener.asciidoc
  documentation/components/tutorial-flow-shortcut.asciidoc
  documentation/creating-components/creating-components-overview.asciidoc
  documentation/element-api/tutorial-dynamic-styling.asciidoc
  documentation/element-api/tutorial-properties-attributes.asciidoc
  documentation/element-api/tutorial-user-input.asciidoc
  documentation/embedding-flow-applications/tutorial-webcomponent-exporter.asciidoc
  documentation/embedding-flow-applications/tutorial-webcomponent-production.asciidoc
  documentation/embedding-flow-applications/tutorial-webcomponent-properties.asciidoc
  documentation/embedding-flow-applications/tutorial-webcomponent-push.asciidoc
  documentation/embedding-flow-applications/tutorial-webcomponent-security.asciidoc
  documentation/embedding-flow-applications/tutorial-webcomponent-theming.asciidoc
  documentation/migration/8-migration-example.asciidoc
  documentation/pom.xml
  documentation/routing/tutorial-router-dynamic-routes.asciidoc
  documentation/routing/tutorial-router-layout.asciidoc
  documentation/routing/tutorial-routing-annotation.asciidoc
  documentation/routing/tutorial-routing-exception-handling.asciidoc
  documentation/routing/tutorial-routing-lifecycle.asciidoc
  documentation/src/main/html/EmbeddedProductionMode.html
  documentation/src/main/html/EmbeddedSecurity.html
  documentation/src/main/html/WebComponentExporter.html
  documentation/src/main/html/WebComponentProperties.html
  documentation/src/main/java/com/vaadin/flow/tutorial/element/DynamicStyling.java
  documentation/src/main/java/com/vaadin/flow/tutorial/element/PropertiesAttributes.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/EmbeddedComponent.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/EmbeddedComponentExporter.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/LoginForm.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/LoginFormExporter.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/MainAppServlet.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/MyExporter.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/PersonComponent.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/PersonExporter.java
  documentation/src/main/java/com/vaadin/flow/tutorial/embeddingflowapplications/PushComponentExporter.java
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/IconButton.java
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/PaperSlider.java
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/b/PaperSlider.java
  documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java
  documentation/web-components/creating-java-api-for-a-web-component.asciidoc
  documentation/web-components/integrating-a-web-component.asciidoc
  pom.xml
  tutorial-getting-started/README.md
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/Customer.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/CustomerService.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/CustomerStatus.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/TutorialGetStartedFirstPart.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/TutorialGetStartedForthPart.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/TutorialGetStartedSecondPart.java
  tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/TutorialGetStartedThirdPart.java
  tutorial-getting-started/src/main/resources/log4j.properties
  tutorial-getting-started/src/main/webapp/frontend/src/example-template.html
  tutorial-getting-started/src/main/webapp/frontend/styles/shared-styles.html
Labels: npm

#587 Document npm goals and remove bower ones
  documentation/production/tutorial-production-mode-advanced.asciidoc
Labels: npm
