Repository vaadin/flow-and-components-documentation, pull requests merged in 2019-03, with the labels that each got.

#492 Element Properties and Attributes
  documentation/element-api/tutorial-properties-attributes.asciidoc
  documentation/src/main/html/Element.html
Labels: BoV

#493 Listening to User Events Using the Element API
  documentation/element-api/tutorial-event-listener.asciidoc
Labels: BoV

#494 Remote Procedure Calls
  documentation/element-api/client-server-rpc.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/element/RPC.java
Labels: BoV

#497 Using the Shadow Root in Server-side Elements
  documentation/element-api/tutorial-shadow-root.asciidoc
Labels: BoV

#507 Update tutorial-enabled-state.asciidoc
  documentation/components/tutorial-enabled-state.asciidoc
Labels: BoV

#505 Update tutorial-flow-components-setup.asciidoc
  documentation/components/tutorial-flow-components-setup.asciidoc
Labels: BoV

#506 Update tutorial-component-basic-features.asciidoc
  documentation/components/tutorial-component-basic-features.asciidoc
Labels: BoV

#508 Update tutorial-flow-grid.asciidoc
  documentation/components/tutorial-flow-grid.asciidoc
Labels: BoV

#509 Update tutorial-flow-upload.asciidoc
  documentation/components/tutorial-flow-upload.asciidoc
Labels: BoV

#519 Update tutorial-component-basic.asciidoc
  documentation/creating-components/tutorial-component-basic.asciidoc
Labels: BoV

#460 Update tutorial-template-basic.asciidoc
  documentation/polymer-templates/tutorial-template-basic.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/polymer/HelloWorldTutorial.java
Labels: waiting for author

#528 Update tutorial-flow-components-setup.asciidoc
  documentation/components/tutorial-flow-components-setup.asciidoc
Labels: to be cherry picked

#533 Fix Introduction to Web Components link
  documentation/web-components/integrating-a-web-component.asciidoc
Labels: to be cherry picked

#556 Add file extension
  documentation/creating-components/creating-components-overview.asciidoc
Labels: to be cherry picked

#558 Use relative link on doc reference
  documentation/migration/8-migration-example.asciidoc
Labels: to be cherry picked

#542 Npm/integrate web component
  docs-helpers/pom.xml
  documentation/pom.xml
  documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/PaperSlider.java
  documentation/web-components/integrating-a-web-component.asciidoc
  pom.xml
  tutorial-binder-with-templates/pom.xml
  tutorial-getting-started/pom.xml
  tutorial-servlet-spring-boot/pom.xml
Labels: npm

#495 Retrieving User Input Using the Element API
  documentation/element-api/tutorial-user-input.asciidoc
Labels: BoV

#496 Dynamic Styling Using the Element API
  documentation/element-api/tutorial-dynamic-styling.asciidoc
  documentation/element-api/tutorial-properties-attributes.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/element/DynamicStyling.java
  documentation/src/main/java/com/vaadin/flow/tutorial/element/PropertiesAttributes.java
Labels: BoV

#504 Update tutorial-flow-shortcut.asciidoc
  documentation/components/tutorial-flow-shortcut.asciidoc
Labels: BoV

#531 Update tutorial-router-dynamic-routes.asciidoc
  documentation/routing/tutorial-router-dynamic-routes.asciidoc
Labels: BoV

#532 Update tutorial-routing-lifecycle.asciidoc
  documentation/routing/tutorial-routing-lifecycle.asciidoc
Labels: BoV
