Repository vaadin/flow-and-components-documentation, pull requests merged in 2019-01, with the labels that each got.

#369 Edited
  documentation/introduction/introduction-overview.asciidoc
Labels: BoV

#389 Edited
  documentation/routing/tutorial-routing-lifecycle.asciidoc
Labels: BoV

#392 Edited
  documentation/routing/tutorial-router-url-parameters.asciidoc
Labels: BoV

#393 Edited
  documentation/routing/tutorial-routing-url-generation.asciidoc
Labels: BoV

#394 Edited
  documentation/routing/tutorial-routing-navigation.asciidoc
Labels: BoV

#397 Edited
  documentation/routing/tutorial-routing-page-titles.asciidoc
Labels: BoV

#395 Edited
  documentation/routing/tutorial-routing-exception-handling.asciidoc
Labels: BoV

#396 Edited
  documentation/routing/tutorial-routing-get-registered-routes.asciidoc
Labels: BoV

#360 Bogdan v10 platform rename
  documentation/Overview.asciidoc
  documentation/cdi/tutorial-cdi-instantiated-beans.asciidoc
  documentation/components/tutorial-flow-components-setup.asciidoc
  documentation/introduction/introduction-overview.asciidoc
  documentation/introduction/tutorial-get-started-first-part.asciidoc
  documentation/introduction/tutorial-get-started-forth-part.asciidoc
  documentation/migration/1-migrating-v8-v10.asciidoc
  documentation/migration/2-migration-strategies.asciidoc
  documentation/migration/3-general-differences.asciidoc
  documentation/migration/4-routing-navigation.asciidoc
  documentation/migration/5-components.asciidoc
  documentation/migration/6-theming.asciidoc
  documentation/migration/7-tools-integrations.asciidoc
  documentation/migration/8-migration-example.asciidoc
  documentation/theme/using-component-themes.asciidoc
Labels: waiting for author

#424 Add CustomField to list of component replacements
  documentation/migration/5-components.asciidoc
Labels: to be cherry picked

#413 Updating basic component features part
  documentation/components/tutorial-component-basic-features.asciidoc
Labels: BoV

#414 Updating enabled state documentation
  documentation/components/tutorial-enabled-state.asciidoc
Labels: BoV

#415 Updating the basic Binder documentation
  documentation/binding-data/tutorial-flow-components-binder.asciidoc
Labels: BoV

#418 Edited tutorial-flow-components-binder-beans
  documentation/binding-data/tutorial-flow-components-binder-beans.asciidoc
Labels: BoV

#417 Edited tutorial-flow-components-binder-load part
  documentation/binding-data/tutorial-flow-components-binder-load.asciidoc
Labels: BoV

#427 Edited - Creating a Component That Has a Value
  documentation/binding-data/tutorial-flow-field.asciidoc
Labels: BoV

#443 Final: Introduction > Introduction to Vaadin Flow
  documentation/introduction/introduction-overview.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/introduction/Introduction.java
Labels: BoV

#419 Edited tutorial-flow-data-provider
  documentation/binding-data/tutorial-flow-data-provider.asciidoc
Labels: BoV

#430 Edited Components > Grid
  documentation/components/tutorial-flow-grid.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/components/GridBasic.java
Labels: BoV

#447 Edited Components > Icon - Jan 24
  documentation/components/tutorial-flow-icon.asciidoc
Labels: BoV

#432 Edited Components > Upload
  documentation/components/tutorial-flow-upload.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/components/UploadBasic.java
Labels: BoV

#436 Edited Including Style Sheets
  documentation/importing-dependencies/tutorial-include-css.asciidoc
Labels: BoV

#438 Edited Ways of Importing Dependencies
  documentation/importing-dependencies/tutorial-importing.asciidoc
  documentation/importing-dependencies/tutorial-ways-of-importing.asciidoc
  documentation/src/main/html/Importing.html
  documentation/src/main/java/com/vaadin/flow/tutorial/importing/Importing.java
  documentation/src/main/java/com/vaadin/flow/tutorial/importing/LazyImporting.java
Labels: BoV

#453 Including Style Sheets - Moved Storing section
  documentation/importing-dependencies/tutorial-include-css.asciidoc
Labels: BoV
