Repository vaadin/flow-and-components-documentation, pull requests merged in 2020-02, with the labels that each got.

#1071 Remove an extra space
  documentation/typescript/check-user-login.asciidoc
Labels: ccdm

#1073 Add Doc regarding Endpoint method name limitation
  documentation/typescript/accessing-backend.asciidoc
Labels: ccdm

#1066 CCDM: adding article describing how to customize serialization
  documentation/Overview.asciidoc
  documentation/src/main/java/com/vaadin/flow/tutorial/typescript/CustomSerialization.java
  documentation/typescript/accessing-backend.asciidoc
  documentation/typescript/custom-serialization.asciidoc
  documentation/typescript/type-conversion.asciidoc
Labels: ccdm

#1069 Update npm pnpm doc
  documentation/advanced/tutorial-switch-npm-pnpm.asciidoc
Labels: ccdm

#1067 CCDM: Add main layout article
  documentation/Overview.asciidoc
  documentation/typescript/main-layout.asciidoc
  documentation/typescript/upgrading-from-vaadin14.asciidoc
  tutorial-binder-with-templates/package-lock.json
  tutorial-binder-with-templates/package.json
Labels: ccdm

#1082 SecurityConfig: align the file name with the class name
  documentation/typescript/adding-login-form-with-spring-security.asciidoc
Labels: ccdm

#1062 explain TS module
  documentation/typescript/accessing-backend.asciidoc
Labels: ccdm

#1083 Update npm pnpm doc
  documentation/advanced/tutorial-switch-npm-pnpm.asciidoc
Labels: ccdm

#1088 Fix the screen recording in accessing Java backend
  documentation/typescript/codecompletion.gif
Labels: ccdm

#1079 CCDM: rename exceptions VaadinConnect -> Endpoint
  documentation/typescript/client-exceptions.asciidoc
  documentation/typescript/endpoint-methods-validation.asciidoc
Labels: ccdm

#1090 link to the Vaadin 15 release page from the quick start guide
  documentation/typescript/quick-start-guide.asciidoc
Labels: ccdm

#1087 CCDM: mention Router TypeScript lifecycle interfaces
  documentation/typescript/creating-routes.asciidoc
  documentation/typescript/intro-to-typescript-in-v15.asciidoc
  documentation/typescript/main-layout.asciidoc
  documentation/typescript/starting-the-app.asciidoc
Labels: ccdm

#1089 Update misleading doc
  documentation/typescript/configuring-security.asciidoc
Labels: ccdm

#1094 use `npm` instead of `pnpm` in the docs for V15
  documentation/typescript/upgrading-from-vaadin14.asciidoc
Labels: ccdm

#1086 mention @AnonymousAllowed in accessing Java backend
  documentation/src/main/java/com/vaadin/flow/tutorial/typescript/AccessingBackend.java
  documentation/typescript/accessing-backend.asciidoc
Labels: ccdm

#1093 fix example docs about generated ts module
  documentation/typescript/accessing-backend.asciidoc
Labels: ccdm

#1081 #1080: links to Tree add-on
  documentation/migration/5-components.asciidoc
Labels: target/v14.1

#1028 Fix introduction JS example
  documentation/introduction/introduction-concepts.asciidoc
Labels: target/V14.1

#1078 Fix formatting
  documentation/workflow/tutorial-plain-servlet-live-reload.asciidoc
Labels: target/V14.1

#1099 Update Doc for pnpm.enable property
  documentation/advanced/tutorial-all-vaadin-properties.asciidoc
Labels: ccdm

#1103 Updating v15 migration doc
  documentation/typescript/upgrading-from-vaadin14.asciidoc
Labels: ccdm
